#!/bin/bash

# Keybind Summary for Hyprland
# Shows all available keybinds without conflicts

echo "=== HYPRLAND KEYBIND SUMMARY ==="
echo ""
echo "🎯 ESSENTIAL SHORTCUTS:"
echo "SUPER + D          - Main Menu (Rofi)"
echo "SUPER + RETURN     - Terminal"
echo "SUPER + E          - File Manager"
echo "SUPER + B          - Default Browser"
echo "SUPER + A          - Desktop Overview"
echo "SUPER + SPACE      - Toggle Floating"
echo "SUPER + Q          - Kill Active Window (from main config)"
echo "SUPER + SHIFT + Q  - Kill Active Process"
echo ""
echo "🖥️ WINDOW MANAGEMENT:"
echo "SUPER + SHIFT + F  - Fullscreen"
echo "SUPER + CTRL + F   - Fake Fullscreen"
echo "SUPER + ALT + F    - Toggle Floating"
echo "SUPER + SHIFT + T  - Toggle Split"
echo "SUPER + TAB        - Cycle Windows"
echo "SUPER + SHIFT + TAB - Cycle Backwards"
echo ""
echo "🏢 WORKSPACE MANAGEMENT:"
echo "SUPER + 1-0        - Switch to Workspace (from main config)"
echo "SUPER + SHIFT + 1-0 - Move Window to Workspace (from main config)"
echo "SUPER + CTRL + W   - Organize Workspaces"
echo "SUPER + CTRL + E   - Switch to Empty Workspace"
echo "SUPER + CTRL + N   - Next Workspace with Windows"
echo "SUPER + CTRL + V   - Previous Workspace with Windows"
echo ""
echo "🎨 THEME & APPEARANCE:"
echo "SUPER + CTRL + T   - Theme Switcher Menu"
echo "SUPER + ALT + R    - Next Theme"
echo "SUPER + ALT + SHIFT + R - Previous Theme"
echo "SUPER + ALT + O    - Toggle Blur"
echo "SUPER + CTRL + O   - Enable Opacity on Active Window"
echo ""
echo "⚙️ SYSTEM CONTROLS:"
echo "SUPER + ALT + Q    - Quick Settings Panel"
echo "SUPER + CTRL + S   - System Tray Menu"
echo "SUPER + CTRL + P   - Performance Monitor"
echo "SUPER + H          - Key Hints"
echo "SUPER + SHIFT + K  - Search Keybinds"
echo "SUPER + SHIFT + A  - Animations Menu"
echo ""
echo "📸 SCREENSHOTS:"
echo "SUPER + PRINT      - Screenshot Now"
echo "SUPER + SHIFT + PRINT - Screenshot Area"
echo "SUPER + CTRL + PRINT - Screenshot (5s delay)"
echo "SUPER + F6         - Screenshot Now (alternative)"
echo "SUPER + SHIFT + F6 - Screenshot Area (alternative)"
echo ""
echo "🎮 GAMING & PERFORMANCE:"
echo "SUPER + SHIFT + G  - Toggle Game Mode"
echo "SUPER + CTRL + P   - Performance Monitor"
echo ""
echo "🔧 UTILITIES:"
echo "SUPER + S          - Google Search (Rofi)"
echo "SUPER + ALT + E    - Emoji Menu"
echo "SUPER + ALT + V    - Clipboard Manager"
echo "SUPER + ALT + C    - Calculator"
echo "SUPER + SHIFT + M  - Online Music"
echo "SUPER + W          - Wallpaper Select"
echo "SUPER + SHIFT + W  - Wallpaper Effects"
echo ""
echo "🎵 MEDIA CONTROLS:"
echo "SUPER + K          - Play/Pause"
echo "SUPER + O          - Next Track"
echo "SUPER + I          - Previous Track"
echo ""
echo "🔒 SYSTEM:"
echo "CTRL + ALT + DELETE - Exit Hyprland"
echo "CTRL + ALT + L     - Lock Screen"
echo "CTRL + ALT + P     - Power Menu"
echo ""
echo "📱 LAPTOP SPECIFIC:"
echo "F6 Keys            - Screenshots (alternative)"
echo "Function Keys      - Volume, Brightness, etc."
echo ""
echo "=== END OF SUMMARY ===" 